# yaml
components_manager:
    components:
        key-value-database:
            dbconnection: mongodb://localhost:27217/admin
            conn_timeout: 15s
            so_timeout: 20s
            queue_timeout: 7s

        handler-key-value:
            path: /v1/key-value
            method: GET,PUT
            task_processor: main-task-processor

        server:
            listener:
                port: 8090
                task_processor: main-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard

        tracer:
            service-name: mongo-service

        dynamic-config:
            fs-cache-path: ''
        dynamic-config-fallbacks:
            fallback-path: /etc/mongo_basic_chaos/dynamic_config_fallback.json
    coro_pool:
        initial_size: 500
        max_size: 1000

    task_processors:
        main-task-processor:
            worker_threads: 4
            thread_name: main-worker

        fs-task-processor:
            thread_name: fs-worker
            worker_threads: 4

    default_task_processor: main-task-processor
